#ifndef GLOBAL_H_INCLUDED
#define GLOBAL_H_INCLUDED
  
#define F_CPU 12000000UL
#ifndef __AVR_ATmega324P__
    #define __AVR_ATmega324P__
#endif

#define GLOBAL_UART0_BITRATE  115200
#define GLOBAL_UART1_BITRATE  115200
#define GLOBAL_UART0_RXBUFSIZE  8
#define GLOBAL_UART0_TXBUFSIZE  128

#define GLOBAL_MODBUS_DEVICEADDR 1
#define GLOBAL_MODBUS_ASCII_BUFSIZE  64
#define GLOBAL_MODBUS_DEBUGLEVEL 0
#define GLOBAL_MODBUS_ECHOREQUEST 1


#define GLOBAL_DEBUG_LEVEL_NONE     0
#define GLOBAL_DEBUG_LEVEL_ERROR   10
#define GLOBAL_DEBUG_LEVEL_WARN    20
#define GLOBAL_DEBUG_LEVEL_INFO    30
#define GLOBAL_DEBUG_LEVEL_FINE    40
#define GLOBAL_DEBUG_LEVEL_FINER   50
#define GLOBAL_DEBUG_LEVEL_FINEST  60
#define GLOBAL_DEBUG_LEVEL_ALL    255

#define GLOBAL_EVENT_MODBUS_ASCII_FRAME 0x01
#define GLOBAL_EVENT_MODBUS_ASCII_ERROR 0x02
#define GLOBAL_EVENT_MODBUS_BUSY        0x04
#define GLOBAL_EVENT_3                  0x08
#define GLOBAL_EVENT_4                  0x10
#define GLOBAL_EVENT_5                  0x20
#define GLOBAL_EVENT_6                  0x40
#define GLOBAL_EVENT_7                  0x80


#endif // GLOBAL_H_INCLUDED
